# Generated by Django 3.2.9 on 2022-08-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220816_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='state',
            field=models.CharField(choices=[('opened', 'Opened'), ('computing', 'Cancelled'), ('delivered ', 'Delivered'), ('null ', 'Null')], default='null ', max_length=50),
        ),
    ]
