# Generated by Django 3.2.9 on 2022-08-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orderitem_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'User Order Summary', 'verbose_name_plural': 'Users Order Summaries'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='state',
            field=models.CharField(choices=[('opened', 'Opened'), ('cancelled', 'Cancelled'), ('delivered ', 'Delivered'), ('null ', 'Null')], default='null ', max_length=50),
        ),
    ]
